### ISSUE TITLE
Create new documentation

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#10]
For someone that is really focused on programming, I am not the best at creating a good readme.md or a great way of making it clear how to start with the project.

I have tried to get this project running on another machine but couldn't get it to work.

Maybe you could help me to document how you can start helping me develop this!

creating good-looking documentation would be really needed here!

**Comment by N3v1** [comment]
I can help if you want 🙂
For examples look at my profile and at my repos 
Link to my profile [**here**](https://github.com/N3v1).

**Comment by N3v1** [comment]
Hi @jiri132 👋,
I have a small question, can I also run the app/program on the Mac? 
If not, I need some screenshots for the new README.md.

Thanks in advance 🙏

**Comment by jiri132** [comment]
Hey @N3v1 👋.
well, I have never tried out if you can run Tauri applications on a Mac but I'll dive into that for you!

Thank you for helping with the project!

**Comment by N3v1** [comment]
Thanks that would be nice 🙏

**Comment by jiri132** [comment]
I have found on the internet that you can develop the application on Mac,
So you can try opening it in the development view using the command `npm run tauri dev` 
Also, I don't have any experience running Tauri applications on Macs.

[source](https://github.com/tauri-apps/tauri) Readme.md > header `operating systems`

If you arent able to get it to open @mention me in this issue and I will try to get back to you ASAP!

**Comment by N3v1** [comment]
Ok @jiri132, I'll try it later and then report back to you if it worked

**Comment by jiri132** [comment]
Hey @N3v1 ,
I have pushed the images to the recent version of `main` ,  it is a set of images before the game, during the game, post-game, selections of menu's, and 50 move rule stalemate of 2 bots

I hope this helps!
if you would like to have a center image of the icon you could leave a suggestion!

kind regards,
JB

**Comment by N3v1** [comment]
Thanks for the pics @jiri132, if I have any questions I'll get back to you.

**Comment by N3v1** [comment]
And it would help me if you wrote me the functionalities of the app

Thank you kindly 🙏
Best regards,
NH

**Comment by N3v1** [comment]
Hello @jiri132 👋,
I've got one more question. What license is your repo released under.

Thank you kindly 🙏
Best regards,
NH

**Comment by jiri132** [comment]
ooh, uhmm....
What is the best license to pick for these types of projects?
I have been only selecting a license for some of it because my classmates advising them 😅

**Comment by N3v1** [comment]
Hi @jiri132 👋,
I actually always use the MIT license but the GNU GLPv3 license is also okay
Here you can find an explanation: (If you want an explanation in English just let me know and I'll find you some in English)
- https://de.wikipedia.org/wiki/Freiz%C3%BCgige_Open-Source-License (German)
- https://www.youtube.com/watch?v=65yaerkySWQ (German)

Thank you kindly 🙏
Best regards,
NH

**Comment by jiri132** [comment]
hey @N3v1 👋 ,
I have read Wikipedia and I'm quite okay with the use of GNU GLPv3 maybe I will switch it much further down the road of this project!

If I can help you any further with the documentation just give me a call!
And also think about if you can make a fun design for the application ;) since you like front-end

Thankyou for contributing 🤝 
Kind regards,
JB

**Comment by N3v1** [comment]
Hi @jiri132 👋,
I'm almost done with the documentation. I will now make a German translation of the README.md. I'll be done by Sunday at the latest, if that's ok with you.

Thank you kindly 🙏
Best regards,
NH

**Comment by N3v1** [comment]
Hi @jiri132 👋,
I have just finished. I'll send you a PR now. If anything is wrong, you can always reach me at `n3v1010@gmail`. If you need help with the documentation in the future, just assign me the tasks.

Thanks again for helping me with your documentation. I'm always happy when I've been able to help other people with my work

Thank you kindly 🙏
Best regards,
NH

**Comment by jiri132** [comment]
Hey @N3v1 ,
I have reviewed everything and the pull requests are accepted I'll close this issue now!
If I have any further things I want with documentation or need help with something I will send you an email.

Kind Regards,
JB
